# Portuguese translation for testdrive
# Copyright (c) 2013 Rosetta Contributors and Canonical Ltd 2013
# This file is distributed under the same license as the testdrive package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: testdrive\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2013-08-02 08:14+1000\n"
"PO-Revision-Date: 2013-08-08 16:30+0000\n"
"Last-Translator: David Pires <Unknown>\n"
"Language-Team: Portuguese <pt@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-08-10 20:12+0000\n"
"X-Generator: Launchpad (build 16723)\n"

#: ../testdrive-gtk.desktop.in.h:1
msgid "Test Drive an Ubuntu ISO"
msgstr "Test Drive uma imagem ISO do Ubuntu"

#: ../testdrive-gtk.desktop.in.h:2
msgid "Download and run an Ubuntu ISO in a Virtual Machine"
msgstr ""
"Faça o download de uma imagem ISO do Ubuntu e instale-a numa máquina virtual"

#: ../testdrive-gtk.desktop.in.h:3
msgid "ISO;Testing;Ubuntu;Daily;VM;Virtual Machine;zsync;rsync;Testdrive"
msgstr "ISO;Testing;Ubuntu;Daily;VM;Virtual Machine;zsync;rsync;Testdrive"

#: ../bin/testdrive-gtk.py:49
msgid "Other"
msgstr "Outro"

#. ##################################################################
#. ####### Obtaining the settings from the Preferences Class ########
#. ##################################################################
#: ../bin/testdrive-gtk.py:139
msgid "Instancing Preferences..."
msgstr "Preferências de Instanciação..."

#: ../bin/testdrive-gtk.py:222
#, python-format
msgid ""
"Checking available ISOs at the ISO tracker [http://iso.qa.ubuntu.com] every "
"%s seconds"
msgstr ""
"Verificação de ISOs disponíveis no rastreador ISO [http://iso.qa.ubuntu.com] "
"a cada% s segundos"

#: ../bin/testdrive-gtk.py:227
msgid "Unable to check the ISO tracker"
msgstr "Não é possível verificar o rastreador ISO"

#: ../bin/testdrive-gtk.py:265
#, python-format
msgid "<b>Release:</b> %s"
msgstr "<b>Lançamento:</b> %s"

#: ../bin/testdrive-gtk.py:266
#, python-format
msgid "<b>ISO Repository:</b> http://%s.ubuntu.com/"
msgstr "<b>Repositório da ISO:</b> http://%s.ubuntu.com/"

#: ../bin/testdrive-gtk.py:306
msgid "Add an ISO to TestDrive"
msgstr "Adicionar uma ISO ao TestDrive"

#: ../bin/testdrive-gtk.py:322
msgid ""
"Unable to open because 'testdrive' is not installed.\n"
"Please install testdrive: \n"
"\n"
"sudo apt-get install testdrive-cli"
msgstr ""
"Não é possível abrir porque o 'testdrive' não está instalado.\n"
"Por favor instale o testdrive: \n"
"\n"
"sudo apt-get install testdrive-cli"

#: ../bin/testdrive-gtk.py:326
msgid "TestDrive an ISO or Disk Image"
msgstr "TestDrive uma ISO ou imagem de disco"

#. ##################################################################
#. ## Obtains the command for the Sync process based on Protocol ####
#. ##################################################################
#: ../bin/testdrive-gtk.py:401
msgid "Obtaining the sync protocol for the specified ISO..."
msgstr "A obter o protocolo de sincronização para a ISO especificada..."

#: ../bin/testdrive-gtk.py:404 ../bin/testdrive.py:375
#, python-format
msgid "Unsupported protocol [%s]"
msgstr "Protocol não suportado [%s]"

#. ##################################################################
#. #### Obtains the Virtualization Method, if not shows warnings ####
#. ##################################################################
#. Choose the virtualization engine
#: ../bin/testdrive-gtk.py:415
msgid "Obtaining the virtualization method..."
msgstr "A obter o método de virtualização..."

#: ../bin/testdrive-gtk.py:419
msgid "Your CPU supports KVM acceleration; please install KVM"
msgstr "O seu processador suporta aceleração KVM; por favor instale KVM"

#: ../bin/testdrive-gtk.py:420
msgid ""
"Your CPU supports KVM acceleration; please install KVM:\n"
"\n"
"sudo apt-get install qemu-kvm"
msgstr ""
"O seu processador suporta aceleração KVM; por favor instale KVM:\n"
"\n"
"sudo apt-get install qemu-kvm"

#: ../bin/testdrive-gtk.py:424
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information; "
"then install VBox"
msgstr ""
"O seu processador não suporta aceleração; execute kvm-ok para mais "
"informação; depois instale VBox"

#: ../bin/testdrive-gtk.py:425
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information;\n"
"then please install VirtualBox\n"
"\n"
"kvm-ok\n"
"sudo apt-get install virtualbox-ose"
msgstr ""
"O seu processador não suporta aceleração; execute kvm-ok para mais "
"informação;\n"
"depois instale VBox\n"
"\n"
"kvm-ok\n"
"sudo apt-get install virtualbox-ose"

#. ##################################################################
#. ### Obtains the list of ISO available from the iso list cache ####
#. ##################################################################
#. Try to retrieve the ISO list from the cache
#: ../bin/testdrive-gtk.py:438 ../bin/testdrive.py:348
msgid "Retrieving the Ubuntu ISO list from cache..."
msgstr "A recuperar a lista ISO do Ubuntu na cache..."

#: ../bin/testdrive-gtk.py:442 ../bin/testdrive-gtk.py:443
#: ../bin/testdrive.py:352
msgid "Unable to retrieve the Ubuntu ISO list from cache..."
msgstr "Não é possível recuperar a lista ISO do Ubuntu na cache..."

#: ../bin/testdrive-gtk.py:563 ../bin/testdrive-gtk.py:598
#: ../bin/testdrive-gtk.py:905
#, python-format
msgid "<i>     CACHE: [%s]</i>"
msgstr "<i> CACHE: [%s]</i>"

#: ../bin/testdrive-gtk.py:565 ../bin/testdrive-gtk.py:600
#: ../bin/testdrive-gtk.py:907
msgid "<i>     CACHE: [empty]</i>"
msgstr "<i> CACHE: [vazia]</i>"

#: ../bin/testdrive-gtk.py:628
msgid "<b><i>There are no Other ISOs yet...</i></b>"
msgstr "<b><i>Ainda não existem outras ISOs...</i></b>"

#: ../bin/testdrive-gtk.py:631
msgid "<b><i>There are no ISOs for this architecture yet...</i></b>"
msgstr "<b><i>Ainda não existem outras ISOs para esta arquitetura...</i></b>"

#. Add Button
#: ../bin/testdrive-gtk.py:665
msgid "Add ISO"
msgstr "Adiccione ISO"

#. Create Buttons
#: ../bin/testdrive-gtk.py:672
msgid "Create USB Disk"
msgstr "Crie um disco USB"

#: ../bin/testdrive-gtk.py:677
msgid "Sync"
msgstr "Sincronização"

#: ../bin/testdrive-gtk.py:682
msgid "Launch"
msgstr "Iniciar"

#: ../bin/testdrive-gtk.py:736 ../bin/testdrive.py:264
msgid "Using KVM for virtual machine hosting..."
msgstr "A usar o KVM para hospedagem de máquinas virtuais..."

#: ../bin/testdrive-gtk.py:739 ../bin/testdrive.py:266
msgid "Using VirtualBox for virtual machine hosting..."
msgstr "A usar o VirtualBox para hospedagem de máquinas virtuais..."

#: ../bin/testdrive-gtk.py:742 ../bin/testdrive.py:268
msgid "Using Parallels Desktop for virtual machine hosting..."
msgstr "A usar o Desktop Parallels para hospedagem de máquinas virtuais..."

#: ../bin/testdrive-gtk.py:796
msgid "sync_iso: Thread is executing..."
msgstr "sync_iso: Thread em execução..."

#: ../bin/testdrive-gtk.py:817
msgid "launch_iso: Thread is executing or syncing..."
msgstr "launch_iso: Thread em execução ou em sincronização..."

#: ../bin/testdrive-gtk.py:824
msgid ""
"No ISO has been selected.\n"
"\n"
"Please select an ISO to create an USB Startup Disk."
msgstr ""
"Não foi selecionada nenhuma ISO.\n"
"\n"
"Por favor selecione uma ISO para criar um disco de arranque USB."

#: ../bin/testdrive-gtk.py:829
msgid ""
"More than 1 ISO has been selected.\n"
"\n"
"Please select only 1 ISO to continue!"
msgstr ""
"Foi selecionada mais do que 1 ISO.\n"
"\n"
"Por favor selecione apenas 1 ISO para continuar!"

#: ../bin/testdrive-gtk.py:834
msgid ""
"The specified ISO does not exist!\n"
"\n"
"Please, synchronize the ISO to continue."
msgstr ""
"A ISO específicada não existe!\n"
"\n"
"Por favor, sincronize a ISO para continuar."

#: ../bin/testdrive-gtk.py:841
msgid "Unable to launch USB Creator!"
msgstr "Não é possível iniciar o USB Creator!"

#: ../bin/testdrive-gtk.py:867
#, python-format
msgid " Downloading %s (0%%)"
msgstr " A transferir %s (0%%)"

#: ../bin/testdrive-gtk.py:887
#, python-format
msgid " Downloading %s (%s%%)"
msgstr " A transferir %s (%s%%)"

#: ../bin/testdrive-gtk.py:936
msgid "    Configuring Virtual Machine..."
msgstr "    A configurar a Máquina Virtual..."

#: ../bin/testdrive-gtk.py:942
msgid "     Running Virtual Machine..."
msgstr "     A executar a Máquina Virtual..."

#: ../bin/testdrive-gtk.py:991
msgid "Show debug messages"
msgstr "Mostrar mensagens de depuração"

#: ../bin/testdrive.py:52
msgid ""
"\n"
"Welcome to Testdrive!\n"
msgstr ""
"\n"
"Bem vindo ao TestDrive!\n"

#: ../bin/testdrive.py:60
#, python-format
msgid "     +-cache--> [%s] %s"
msgstr "     +-cache--> [%s] %s"

#: ../bin/testdrive.py:63
#, python-format
msgid "  %d. Other (prompt for ISO URL)"
msgstr "  %d. Outro (prompt para URL da  ISO)"

#: ../bin/testdrive.py:65
msgid ""
"\n"
"Select an image to testdrive [1]: "
msgstr ""
"\n"
"Selecione uma imagem para o testdrive [1]: "

#: ../bin/testdrive.py:74
msgid ""
"\n"
"ERROR: Invalid input\n"
msgstr ""
"\n"
"ERRO: Entrada inválida\n"

#: ../bin/testdrive.py:77
msgid ""
"\n"
"Enter an ISO URL to testdrive: "
msgstr ""
"\n"
"Introduza o URL da ISO para testdrive: "

#: ../bin/testdrive.py:84
msgid ""
"\n"
"ERROR: Invalid selection\n"
msgstr ""
"\n"
"ERRO: Seleção inválida\n"

#: ../bin/testdrive.py:88
#, python-format
msgid ""
"\n"
"%s\n"
msgstr ""
"\n"
"%s\n"

#: ../bin/testdrive.py:102 ../testdrivegtk/AddOtherTestdrivegtkDialog.py:155
#, python-format
msgid "Invalid ISO URL [%s]"
msgstr "ISO URL [%s] inválida"

#: ../bin/testdrive.py:144
#, python-format
msgid ""
"Command failed\n"
"    `%s`"
msgstr ""
"Comando falhado\n"
"    `%s`"

#: ../bin/testdrive.py:151
msgid "Launching Virtual Machine using CURSES as screen mode"
msgstr "Lançamento da Máquina Virtual usando o CURSES como modo de ecrã"

#: ../bin/testdrive.py:196
msgid "user configuration file (overriding default values"
msgstr ""
"ficheiro de configuração do utilizador (a sobrescrever os valores "
"predefinidos"

#: ../bin/testdrive.py:198
msgid "print version and system data, and exit"
msgstr "imprimir dados e versão do sistema, e sair"

#: ../bin/testdrive.py:200
msgid "get ISO image from this URL location"
msgstr "obter imagem ISO a partir desta localização URL"

#: ../bin/testdrive.py:202
msgid "try to launch usb-creator for further testing"
msgstr "tentar lançar o usb-creator para testes adicionais"

#: ../bin/testdrive.py:204
msgid "hardcode Ubuntu RELEASE codename"
msgstr "nome de código de LANÇAMENTO hardcode Ubuntu"

#: ../bin/testdrive.py:206
msgid ""
"hardcode Ubuntu flavor. Available Flavors:\n"
"             "
"ubuntu/kubuntu/xubuntu/edubuntu/mythbuntu/ubuntustudio/lubuntu/ubuntukylin"
msgstr ""
"Distribuição Ubuntu hardcode. Distribuições disponíveis:\n"
"             "
"ubuntu/kubuntu/xubuntu/edubuntu/mythbuntu/ubuntustudio/lubuntu/ubuntukylin"

#: ../bin/testdrive.py:209
msgid ""
"hardcode Ubuntu repository from where to obtain ISOs:\n"
"             releases/cdimage/cloud-daily/cloud-releases"
msgstr ""
"repositório Ubuntu hardcode a partir de onde obter ISOs:\n"
"             releases/cdimage/cloud-daily/cloud-releases"

#: ../bin/testdrive.py:212
msgid ""
"displays the Virtual Machine in the shell. Only valid for Cloud images."
msgstr ""
"exibe a Máquina Virtual na shell. Válido somente para imagens na nuvem."

#: ../bin/testdrive.py:217
#, python-format
msgid "version passed: %s"
msgstr "versão aprovada: %s"

#: ../bin/testdrive.py:221
#, python-format
msgid "testdrive %s"
msgstr "testdrive %s"

#: ../bin/testdrive.py:233
#, python-format
msgid "config passed: %s"
msgstr "config aprovado: %s"

#: ../bin/testdrive.py:243
#, python-format
msgid "Trying config in %s"
msgstr "A tentar config em %s"

#: ../bin/testdrive.py:247
#, python-format
msgid "Using configuration in %s"
msgstr "A usar a configuração em %s"

#: ../bin/testdrive.py:249
#, python-format
msgid "Invalid configuration [%s]"
msgstr "Configuração inválida [%s]"

#: ../bin/testdrive.py:257
msgid ""
"Your CPU supports KVM acceleration; please install KVM:\n"
"            sudo apt-get install qemu-kvm"
msgstr ""
"O seu processador suporta aceleração KVM, por favor instalar KVM:\n"
"            sudo apt-get install qemu-kvm"

#: ../bin/testdrive.py:260
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information; "
"then please install VirtualBox:\n"
"            kvm-ok\n"
"            sudo apt-get install virtualbox-ose"
msgstr ""
"O seu processador não suporta aceleração; execute kvm-ok para mais "
"informações, depois por favor instale o VirtualBox:\n"
"            kvm-ok\n"
"            sudo apt-get install virtualbox-ose"

#: ../bin/testdrive.py:284
msgid ""
"Launching Cloud images only works with KVM. Please switch your "
"virtualization method..."
msgstr ""
"O lançamento de imagens na nuvem só funciona com KVM. Por favor, mude o seu "
"método de virtualização ..."

#: ../bin/testdrive.py:335
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:333
#, python-format
msgid "Obtaining Ubuntu ISO list from %s..."
msgstr "A obter a lista Ubuntu ISO de %s..."

#: ../bin/testdrive.py:339
#, python-format
msgid "ERROR: Could not obtain the Ubuntu ISO list from %s..."
msgstr "ERRO: Não foi possível obter a lista Ubuntu ISO de %s..."

#: ../bin/testdrive.py:345
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:345
msgid "Unable to update the Ubuntu ISO list cache..."
msgstr "Não é possível atualizar a lista Ubunto ISO da cache..."

#. BUG: should check disk space availability in CACHE dir
#. Update the cache
#: ../bin/testdrive.py:371
msgid "Syncing the specified ISO..."
msgstr "A sincronizar a ISO especificada..."

#: ../bin/testdrive.py:378 ../testdrivegtk/AddOtherTestdrivegtkDialog.py:167
#, python-format
msgid "ISO not found at [%s]"
msgstr "ISO não encontrada em [%s]"

#. ##################
#. # Launch the VM ##
#. ##################
#: ../bin/testdrive.py:401
msgid "Validating Virtualization Method...."
msgstr "A validar o Método de Virtualização..."

#: ../bin/testdrive.py:405
#, python-format
msgid "Unable to validate Virtualization Method [%s]"
msgstr "Não é possível validar o Método de Virtualização [%s]"

#: ../bin/testdrive.py:407
msgid "Setting up Virtual Machine..."
msgstr "A configurar a Máquina Virtual..."

#: ../bin/testdrive.py:411
msgid "Unable to setup Virtual Machine"
msgstr "Não é possível configurar a Máquina Virtual"

#: ../bin/testdrive.py:413
msgid "Launching Virtual Machine..."
msgstr "A iniciar a Máquina Virtual..."

#: ../bin/testdrive.py:421
msgid "Unable to launch Virtual Machine"
msgstr "Não é possível iniciar a Máquina Virtual"

#: ../bin/testdrive.py:425
#, python-format
msgid "Cleaning up disk image [%s]..."
msgstr "A limpar a imagem de disco [%s]..."

#. Remind about cache cleanup
#: ../bin/testdrive.py:428
msgid "You may wish to clean up the cache directory..."
msgstr "Pode querer limpar a diretoria da cache..."

#: ../bin/testdrive.py:429
#, python-format
msgid "      %s and %s"
msgstr "      %s e %s"

#: ../bin/testdrive.py:436
msgid ""
"\n"
"Launch USB Startup Disk Creator for further testing of this ISO? [y/N] "
msgstr ""
"\n"
"Iniciar o USB Startup Disk Creator para testes adicionais desta ISO? [y/N] "

#: ../bin/testdrive.py:440
msgid ""
"\n"
"Press <enter> to exit..."
msgstr ""
"\n"
"Pressionar <enter> para sair..."

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:135
msgid "Please insert a Description"
msgstr "Por favor insira uma Descrição"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:140
msgid "Please insert a URL"
msgstr "Por favor insira um URL"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:171
msgid "No sync protocol has been selected, please select one."
msgstr ""
"Não foi selecionado nenhum protocolo de sincronização, por favor selecione "
"um."

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:196
msgid "Description"
msgstr "Descrição"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:227
msgid "Select Protocol:"
msgstr "Selecione Protocolo:"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:36
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:37
msgid "Other..."
msgstr "Outro..."

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:72
msgid "TestDrive Preferences"
msgstr "Preferências do TestDrive"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:98
msgid "finish_initialization()"
msgstr "finish_initialization()"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:138
msgid "Select Repository:"
msgstr "Selecione Repositório:"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:149
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:490
msgid "Select Release:"
msgstr "Selecione a Edição"

#. Load config files for local variables
#. self.load_config_files(file)
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:217
#, python-format
msgid "Reading config file: [%s]"
msgstr "A ler o ficheiro [%s] config"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:219
#, python-format
msgid "Unable to load config file [%s]"
msgstr "Não é possível carregar o ficheiro [%s] config"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:276
#, python-format
msgid " of %s available."
msgstr " de [%s] disponíveis."

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:337
#, python-format
msgid "Could not obtain the Ubuntu ISO list from %s..."
msgstr "Não foi possível obter a lista Ubuntu ISO de %s..."

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:341
msgid "Updating the Ubuntu ISO list cache..."
msgstr "A atualizar a lista Ubuntu ISO da cache..."

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:349
msgid "get_preferences()"
msgstr "get_preferences()"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:472
#, python-format
msgid "Unable to clean up files from [%s]"
msgstr "Não é possível limpar os ficheiros de [%s]"
