# German translation for testdrive
# Copyright (c) 2010 Rosetta Contributors and Canonical Ltd 2010
# This file is distributed under the same license as the testdrive package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: testdrive\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2013-08-02 08:14+1000\n"
"PO-Revision-Date: 2010-09-01 21:28+0000\n"
"Last-Translator: Daniel Schury <das.surst@gmail.com>\n"
"Language-Team: German <de@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-08-10 20:12+0000\n"
"X-Generator: Launchpad (build 16723)\n"

#: ../testdrive-gtk.desktop.in.h:1
msgid "Test Drive an Ubuntu ISO"
msgstr "Ein Ubuntu-Abbild testen"

#: ../testdrive-gtk.desktop.in.h:2
msgid "Download and run an Ubuntu ISO in a Virtual Machine"
msgstr ""
"Ein Ubuntu-Abbild herunterladen und in einer virtuellen Maschine testen"

#: ../testdrive-gtk.desktop.in.h:3
msgid "ISO;Testing;Ubuntu;Daily;VM;Virtual Machine;zsync;rsync;Testdrive"
msgstr ""

#: ../bin/testdrive-gtk.py:49
msgid "Other"
msgstr "Weitere"

#. ##################################################################
#. ####### Obtaining the settings from the Preferences Class ########
#. ##################################################################
#: ../bin/testdrive-gtk.py:139
msgid "Instancing Preferences..."
msgstr "Ermittle Einstellungen …"

#: ../bin/testdrive-gtk.py:222
#, python-format
msgid ""
"Checking available ISOs at the ISO tracker [http://iso.qa.ubuntu.com] every "
"%s seconds"
msgstr ""

#: ../bin/testdrive-gtk.py:227
msgid "Unable to check the ISO tracker"
msgstr ""

#: ../bin/testdrive-gtk.py:265
#, python-format
msgid "<b>Release:</b> %s"
msgstr "<b>Veröffentlichung:</b> %s"

#: ../bin/testdrive-gtk.py:266
#, python-format
msgid "<b>ISO Repository:</b> http://%s.ubuntu.com/"
msgstr "<b>Abbildpaketquelle:</b> http://%s.ubuntu.com/"

#: ../bin/testdrive-gtk.py:306
msgid "Add an ISO to TestDrive"
msgstr "Ein Abbild zu TestDrive hinzufügen"

#: ../bin/testdrive-gtk.py:322
msgid ""
"Unable to open because 'testdrive' is not installed.\n"
"Please install testdrive: \n"
"\n"
"sudo apt-get install testdrive-cli"
msgstr ""
"Konnte nicht geöffnet werden, weil »testdrive« nicht installiert ist.\n"
"Bitte installieren Sie testdrive: \n"
"\n"
"sudo apt-get install testdrive-cli"

#: ../bin/testdrive-gtk.py:326
msgid "TestDrive an ISO or Disk Image"
msgstr "Ein ISO- oder Datenträgerabbild mit TestDrive testen"

#. ##################################################################
#. ## Obtains the command for the Sync process based on Protocol ####
#. ##################################################################
#: ../bin/testdrive-gtk.py:401
msgid "Obtaining the sync protocol for the specified ISO..."
msgstr "Ermittle das Synchronisierungsprotokoll des angegebenen Abbilds …"

#: ../bin/testdrive-gtk.py:404 ../bin/testdrive.py:375
#, python-format
msgid "Unsupported protocol [%s]"
msgstr "Nicht unterstütztes Protokoll [%s]"

#. ##################################################################
#. #### Obtains the Virtualization Method, if not shows warnings ####
#. ##################################################################
#. Choose the virtualization engine
#: ../bin/testdrive-gtk.py:415
msgid "Obtaining the virtualization method..."
msgstr "Ermittle die Virtualisierungsmethode …"

#: ../bin/testdrive-gtk.py:419
msgid "Your CPU supports KVM acceleration; please install KVM"
msgstr ""
"Ihr Prozessor unterstützt KVM-Beschleunigung; Bitte installieren Sie KVM"

#: ../bin/testdrive-gtk.py:420
msgid ""
"Your CPU supports KVM acceleration; please install KVM:\n"
"\n"
"sudo apt-get install qemu-kvm"
msgstr ""
"Ihr Prozessor unterstützt KVM-Beschleunigung; Bitte installieren Sie KVM:\n"
"\n"
"sudo apt-get install qemu-kvm"

#: ../bin/testdrive-gtk.py:424
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information; "
"then install VBox"
msgstr ""
"Ihr Prozessor unterstützt keine Beschleunigung; Führen Sie kvm-ok für "
"weitere Informationen aus und installieren Sie anschließend VBox"

#: ../bin/testdrive-gtk.py:425
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information;\n"
"then please install VirtualBox\n"
"\n"
"kvm-ok\n"
"sudo apt-get install virtualbox-ose"
msgstr ""
"Ihr Prozessor unterstützt keine Beschleunigung; Führen Sie kvm-ok für "
"weitere Informationen aus und installieren Sie anschließend VBox\n"
"\n"
"kvm-ok\n"
"sudo apt-get install virtualbox-ose"

#. ##################################################################
#. ### Obtains the list of ISO available from the iso list cache ####
#. ##################################################################
#. Try to retrieve the ISO list from the cache
#: ../bin/testdrive-gtk.py:438 ../bin/testdrive.py:348
msgid "Retrieving the Ubuntu ISO list from cache..."
msgstr "Beziehe die Ubuntu-Abbildliste aus dem Zwischenspeicher …"

#: ../bin/testdrive-gtk.py:442 ../bin/testdrive-gtk.py:443
#: ../bin/testdrive.py:352
msgid "Unable to retrieve the Ubuntu ISO list from cache..."
msgstr "Konnte die Ubuntu-Abbildliste nicht aus dem Zwischenspeicher lesen …"

#: ../bin/testdrive-gtk.py:563 ../bin/testdrive-gtk.py:598
#: ../bin/testdrive-gtk.py:905
#, python-format
msgid "<i>     CACHE: [%s]</i>"
msgstr "<i>     ZWISCHENSPEICHER: [%s]</i>"

#: ../bin/testdrive-gtk.py:565 ../bin/testdrive-gtk.py:600
#: ../bin/testdrive-gtk.py:907
msgid "<i>     CACHE: [empty]</i>"
msgstr "<i>     ZWISCHENSPEICHER: [leer]</i>"

#: ../bin/testdrive-gtk.py:628
msgid "<b><i>There are no Other ISOs yet...</i></b>"
msgstr "<b><i>Dort sind zur Zeit keine anderen Abbilder …</i></b>"

#: ../bin/testdrive-gtk.py:631
msgid "<b><i>There are no ISOs for this architecture yet...</i></b>"
msgstr ""
"<b><i>Dort sind zur Zeit keine anderen Abbilder für diese Architektur "
"…</i></b>"

#. Add Button
#: ../bin/testdrive-gtk.py:665
msgid "Add ISO"
msgstr "Abbild hinzufügen"

#. Create Buttons
#: ../bin/testdrive-gtk.py:672
msgid "Create USB Disk"
msgstr "USB-Datenträger erstellen"

#: ../bin/testdrive-gtk.py:677
msgid "Sync"
msgstr "Synchronisieren"

#: ../bin/testdrive-gtk.py:682
msgid "Launch"
msgstr "Starten"

#: ../bin/testdrive-gtk.py:736 ../bin/testdrive.py:264
msgid "Using KVM for virtual machine hosting..."
msgstr "Verwende KVM als virtuelle Maschine …"

#: ../bin/testdrive-gtk.py:739 ../bin/testdrive.py:266
msgid "Using VirtualBox for virtual machine hosting..."
msgstr "Verwende VirtualBox als virtuelle Maschine …"

#: ../bin/testdrive-gtk.py:742 ../bin/testdrive.py:268
msgid "Using Parallels Desktop for virtual machine hosting..."
msgstr "Verwende Parallels Desktop als virtuelle Maschine …"

#: ../bin/testdrive-gtk.py:796
msgid "sync_iso: Thread is executing..."
msgstr "sync_iso: Thread wird ausgeführt …"

#: ../bin/testdrive-gtk.py:817
msgid "launch_iso: Thread is executing or syncing..."
msgstr "launch_iso: Thread wird ausgeführt oder synchronisiert …"

#: ../bin/testdrive-gtk.py:824
msgid ""
"No ISO has been selected.\n"
"\n"
"Please select an ISO to create an USB Startup Disk."
msgstr ""
"Es wurde kein Abbild ausgewählt.\n"
"\n"
"Bitte wählen Sie ein Abbild aus, um einen USB-Startdatenträger zu erstellen."

#: ../bin/testdrive-gtk.py:829
msgid ""
"More than 1 ISO has been selected.\n"
"\n"
"Please select only 1 ISO to continue!"
msgstr ""
"Mehr als ein Abbild wurde ausgewählt.\n"
"\n"
"Bitte wählen Sie nur ein Abbild aus, um fortzufahren!"

#: ../bin/testdrive-gtk.py:834
msgid ""
"The specified ISO does not exist!\n"
"\n"
"Please, synchronize the ISO to continue."
msgstr ""
"Das angegebene Abbild existiert nicht!\n"
"\n"
"Bitte synchronisieren Sie Ihre Abbilder um fortzufahren."

#: ../bin/testdrive-gtk.py:841
msgid "Unable to launch USB Creator!"
msgstr "USB-Erstellungsprogramm konnte nicht gestartet werden!"

#: ../bin/testdrive-gtk.py:867
#, python-format
msgid " Downloading %s (0%%)"
msgstr ""

#: ../bin/testdrive-gtk.py:887
#, python-format
msgid " Downloading %s (%s%%)"
msgstr ""

#: ../bin/testdrive-gtk.py:936
msgid "    Configuring Virtual Machine..."
msgstr ""

#: ../bin/testdrive-gtk.py:942
msgid "     Running Virtual Machine..."
msgstr ""

#: ../bin/testdrive-gtk.py:991
msgid "Show debug messages"
msgstr "Debug-Meldungen anzeigen"

#: ../bin/testdrive.py:52
msgid ""
"\n"
"Welcome to Testdrive!\n"
msgstr ""
"\n"
"Willkommen zu TestDrive!\n"

#: ../bin/testdrive.py:60
#, python-format
msgid "     +-cache--> [%s] %s"
msgstr "     +-Speicher-->[%s] %s"

#: ../bin/testdrive.py:63
#, python-format
msgid "  %d. Other (prompt for ISO URL)"
msgstr "  %d. Andere (Eingabe für Abbild-URL)"

#: ../bin/testdrive.py:65
msgid ""
"\n"
"Select an image to testdrive [1]: "
msgstr ""
"\n"
"Wähle ein Abbild für testdrive aus [1]: "

#: ../bin/testdrive.py:74
msgid ""
"\n"
"ERROR: Invalid input\n"
msgstr ""
"\n"
"FEHLER: Ungültige Eingabe\n"

#: ../bin/testdrive.py:77
msgid ""
"\n"
"Enter an ISO URL to testdrive: "
msgstr ""
"\n"
"Geben Sie eine Abbild-URL für testdrive an: "

#: ../bin/testdrive.py:84
msgid ""
"\n"
"ERROR: Invalid selection\n"
msgstr ""
"\n"
"FEHLER: Ungültiger Abschnitt\n"

#: ../bin/testdrive.py:88
#, python-format
msgid ""
"\n"
"%s\n"
msgstr ""

#: ../bin/testdrive.py:102 ../testdrivegtk/AddOtherTestdrivegtkDialog.py:155
#, python-format
msgid "Invalid ISO URL [%s]"
msgstr "Ungültige Abbild-URL [%s]"

#: ../bin/testdrive.py:144
#, python-format
msgid ""
"Command failed\n"
"    `%s`"
msgstr ""
"Befehl fehlgeschlagen\n"
"    »%s«"

#: ../bin/testdrive.py:151
msgid "Launching Virtual Machine using CURSES as screen mode"
msgstr ""

#: ../bin/testdrive.py:196
msgid "user configuration file (overriding default values"
msgstr "Benutzerkonfigurationsdatei (Überschreibt Vorgabewerte)"

#: ../bin/testdrive.py:198
msgid "print version and system data, and exit"
msgstr "Version und Systemdaten ausgeben und beenden"

#: ../bin/testdrive.py:200
msgid "get ISO image from this URL location"
msgstr "Abbild von dieser URL erhalten"

#: ../bin/testdrive.py:202
msgid "try to launch usb-creator for further testing"
msgstr "Versuchen dasUSB-Erstellungsprogramm für weitere Tests starten"

#: ../bin/testdrive.py:204
msgid "hardcode Ubuntu RELEASE codename"
msgstr "Fest programmierte Ubuntu-VERSION-Codename"

#: ../bin/testdrive.py:206
msgid ""
"hardcode Ubuntu flavor. Available Flavors:\n"
"             "
"ubuntu/kubuntu/xubuntu/edubuntu/mythbuntu/ubuntustudio/lubuntu/ubuntukylin"
msgstr ""

#: ../bin/testdrive.py:209
msgid ""
"hardcode Ubuntu repository from where to obtain ISOs:\n"
"             releases/cdimage/cloud-daily/cloud-releases"
msgstr ""

#: ../bin/testdrive.py:212
msgid ""
"displays the Virtual Machine in the shell. Only valid for Cloud images."
msgstr ""

#: ../bin/testdrive.py:217
#, python-format
msgid "version passed: %s"
msgstr "Getestete Version: %s"

#: ../bin/testdrive.py:221
#, python-format
msgid "testdrive %s"
msgstr "testdrive %s"

#: ../bin/testdrive.py:233
#, python-format
msgid "config passed: %s"
msgstr "Getestete Einstellung: %s"

#: ../bin/testdrive.py:243
#, python-format
msgid "Trying config in %s"
msgstr "Teste Konfiguration in %s"

#: ../bin/testdrive.py:247
#, python-format
msgid "Using configuration in %s"
msgstr "Verwende Einstellungen in %s"

#: ../bin/testdrive.py:249
#, python-format
msgid "Invalid configuration [%s]"
msgstr "Fehlerhafte Einstellungen [%s]"

#: ../bin/testdrive.py:257
msgid ""
"Your CPU supports KVM acceleration; please install KVM:\n"
"            sudo apt-get install qemu-kvm"
msgstr ""

#: ../bin/testdrive.py:260
msgid ""
"Your CPU does not support acceleration; run kvm-ok for more information; "
"then please install VirtualBox:\n"
"            kvm-ok\n"
"            sudo apt-get install virtualbox-ose"
msgstr ""

#: ../bin/testdrive.py:284
msgid ""
"Launching Cloud images only works with KVM. Please switch your "
"virtualization method..."
msgstr ""

#: ../bin/testdrive.py:335
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:333
#, python-format
msgid "Obtaining Ubuntu ISO list from %s..."
msgstr "Ubuntu-Abbildliste wird von %s geladen …"

#: ../bin/testdrive.py:339
#, python-format
msgid "ERROR: Could not obtain the Ubuntu ISO list from %s..."
msgstr "FEHLER: Konnte das Ubuntu-Ablist nicht von der Liste %s beziehen …"

#: ../bin/testdrive.py:345
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:345
msgid "Unable to update the Ubuntu ISO list cache..."
msgstr "Der Ubuntu-Abbildspeicher konnte nicht aktualisiert werden …"

#. BUG: should check disk space availability in CACHE dir
#. Update the cache
#: ../bin/testdrive.py:371
msgid "Syncing the specified ISO..."
msgstr "Synchronisiere das ausgewählte Abbild …"

#: ../bin/testdrive.py:378 ../testdrivegtk/AddOtherTestdrivegtkDialog.py:167
#, python-format
msgid "ISO not found at [%s]"
msgstr "Abbild wurde nicht unter [%s] gefunden"

#. ##################
#. # Launch the VM ##
#. ##################
#: ../bin/testdrive.py:401
msgid "Validating Virtualization Method...."
msgstr "Virtualisierungsmethode wird validiert …"

#: ../bin/testdrive.py:405
#, python-format
msgid "Unable to validate Virtualization Method [%s]"
msgstr "Konnte Virtualisierungsmethode [%s] nicht validieren"

#: ../bin/testdrive.py:407
msgid "Setting up Virtual Machine..."
msgstr "Virtuelle Maschine wird eingerichtet …"

#: ../bin/testdrive.py:411
msgid "Unable to setup Virtual Machine"
msgstr "Virtuelle Maschine konnte nicht eingerichtet werden"

#: ../bin/testdrive.py:413
msgid "Launching Virtual Machine..."
msgstr "Virtuelle Maschine wird gestartet …"

#: ../bin/testdrive.py:421
msgid "Unable to launch Virtual Machine"
msgstr "Virtuelle Maschine konnte nicht gestartet werden"

#: ../bin/testdrive.py:425
#, python-format
msgid "Cleaning up disk image [%s]..."
msgstr "Festplattenabbild [%s] wird bereinigt …"

#. Remind about cache cleanup
#: ../bin/testdrive.py:428
msgid "You may wish to clean up the cache directory..."
msgstr "Eventuell sollten Sie noch den Zwischenspeicherordner aufräumen …"

#: ../bin/testdrive.py:429
#, python-format
msgid "      %s and %s"
msgstr "      %s und %s"

#: ../bin/testdrive.py:436
msgid ""
"\n"
"Launch USB Startup Disk Creator for further testing of this ISO? [y/N] "
msgstr ""
"\n"
"USB-Startmedienersteller für weitere Tests des Abbilds starten? [y/N] "

#: ../bin/testdrive.py:440
msgid ""
"\n"
"Press <enter> to exit..."
msgstr ""
"\n"
"<enter> zum Beenden eingeben …"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:135
msgid "Please insert a Description"
msgstr "Bitte geben Sie eine Beschreibung ein"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:140
msgid "Please insert a URL"
msgstr "Bitte geben Sie eine URL ein"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:171
msgid "No sync protocol has been selected, please select one."
msgstr ""
"Es wurde kein Synchronisationsprotokoll ausgewählt, bitte wählen Sie eins "
"aus."

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:196
msgid "Description"
msgstr "Beschreibung"

#: ../testdrivegtk/AddOtherTestdrivegtkDialog.py:227
msgid "Select Protocol:"
msgstr "Protokoll auswählen:"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:36
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:37
msgid "Other..."
msgstr "Andere ..."

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:72
msgid "TestDrive Preferences"
msgstr "TestDrive-Einstellungen"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:98
msgid "finish_initialization()"
msgstr "finish_initialization()"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:138
msgid "Select Repository:"
msgstr "Paketquelle auswählen:"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:149
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:490
msgid "Select Release:"
msgstr "Veröffentlichung auswählen:"

#. Load config files for local variables
#. self.load_config_files(file)
#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:217
#, python-format
msgid "Reading config file: [%s]"
msgstr "Konfigurationsdatei auswählen: [%s]"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:219
#, python-format
msgid "Unable to load config file [%s]"
msgstr "Konfigurationsdatei [%s] konnte nicht geladen werden"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:276
#, python-format
msgid " of %s available."
msgstr " von %s verfügbar."

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:337
#, python-format
msgid "Could not obtain the Ubuntu ISO list from %s..."
msgstr "Konnte die Ubuntu-Abbildliste nicht von %s laden …"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:341
msgid "Updating the Ubuntu ISO list cache..."
msgstr "Ubuntu-Abbildspeicher wird aktualisirt …"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:349
msgid "get_preferences()"
msgstr "get_preferences()"

#: ../testdrivegtk/PreferencesTestdrivegtkDialog.py:472
#, python-format
msgid "Unable to clean up files from [%s]"
msgstr "Dateien konnten nicht aus [%s] aufgeräumt werden"
